# Generated by Django 4.1.5 on 2023-01-30 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('response_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('request_text', models.TextField()),
                ('speaker_name', models.CharField(max_length=200)),
                ('speaker_token', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('response_audio_file', models.FileField(blank=True, null=True, upload_to='')),
                ('response_audio_url', models.CharField(blank=True, max_length=255, null=True)),
                ('chat_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='speechwriter.chatresponse')),
            ],
        ),
        migrations.AddField(
            model_name='chatresponse',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='speechwriter.request'),
        ),
    ]
